# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Fontys/Impl_PID/Impl_PID.srcs/sources_1/bd/impl/ip/impl_clk_wiz_8/impl_clk_wiz_8.xci
# IP: The module: 'impl_clk_wiz_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Fontys/Impl_PID/Impl_PID.gen/sources_1/bd/impl/ip/impl_clk_wiz_8/impl_clk_wiz_8_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'impl_clk_wiz_8'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Fontys/Impl_PID/Impl_PID.gen/sources_1/bd/impl/ip/impl_clk_wiz_8/impl_clk_wiz_8.xdc
# XDC: The top module name and the constraint reference have the same name: 'impl_clk_wiz_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Fontys/Impl_PID/Impl_PID.gen/sources_1/bd/impl/ip/impl_clk_wiz_8/impl_clk_wiz_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'impl_clk_wiz_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Fontys/Impl_PID/Impl_PID.srcs/sources_1/bd/impl/ip/impl_clk_wiz_8/impl_clk_wiz_8.xci
# IP: The module: 'impl_clk_wiz_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Fontys/Impl_PID/Impl_PID.gen/sources_1/bd/impl/ip/impl_clk_wiz_8/impl_clk_wiz_8_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'impl_clk_wiz_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Fontys/Impl_PID/Impl_PID.gen/sources_1/bd/impl/ip/impl_clk_wiz_8/impl_clk_wiz_8.xdc
# XDC: The top module name and the constraint reference have the same name: 'impl_clk_wiz_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Fontys/Impl_PID/Impl_PID.gen/sources_1/bd/impl/ip/impl_clk_wiz_8/impl_clk_wiz_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'impl_clk_wiz_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
