# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Fontys/Impl_PID/Impl_PID.srcs/sources_1/bd/impl/ip/impl_rst_clk_wiz_100M_0/impl_rst_clk_wiz_100M_0.xci
# IP: The module: 'impl_rst_clk_wiz_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Fontys/Impl_PID/Impl_PID.gen/sources_1/bd/impl/ip/impl_rst_clk_wiz_100M_0/impl_rst_clk_wiz_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'impl_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Fontys/Impl_PID/Impl_PID.gen/sources_1/bd/impl/ip/impl_rst_clk_wiz_100M_0/impl_rst_clk_wiz_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'impl_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Fontys/Impl_PID/Impl_PID.gen/sources_1/bd/impl/ip/impl_rst_clk_wiz_100M_0/impl_rst_clk_wiz_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'impl_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Fontys/Impl_PID/Impl_PID.srcs/sources_1/bd/impl/ip/impl_rst_clk_wiz_100M_0/impl_rst_clk_wiz_100M_0.xci
# IP: The module: 'impl_rst_clk_wiz_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Fontys/Impl_PID/Impl_PID.gen/sources_1/bd/impl/ip/impl_rst_clk_wiz_100M_0/impl_rst_clk_wiz_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'impl_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Fontys/Impl_PID/Impl_PID.gen/sources_1/bd/impl/ip/impl_rst_clk_wiz_100M_0/impl_rst_clk_wiz_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'impl_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Fontys/Impl_PID/Impl_PID.gen/sources_1/bd/impl/ip/impl_rst_clk_wiz_100M_0/impl_rst_clk_wiz_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'impl_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
